#!/bin/sh

#chkconfig: 123456 90 10

# openerp server for user authentication


daemon_start() {
    echo "Server started."
    /usr/bin/virt-monitor start
}

daemon_stop() {

    /usr/bin/virt-monitor stop

    sleep 1

    echo "Server killed."

}

case "$1" in

start)

    daemon_start

    ;;

stop)

    daemon_stop

    ;;

restart)

    daemon_stop

    daemon_start

    ;;

*)

    echo "Usage:  /usr/bin/virt-monitor {start|stop|restart}"

    exit 1

esac

exit 0