#! /bin/bash
###############################################
##
##  Copyright (2019, ) Institute of Software
##      Chinese Academy of Sciences
##          wuheng@otcaixiscas.ac.cn
##         wuyuewen@otcaix.iscas.ac.cn
##              2019-9-24
##
###############################################

function init-env()
{
  swapoff -a
  systemctl stop firewalld
  systemctl disable firewalld

  res=$(cat /etc/sysctl.conf | grep swappiness)
  sysctl net.bridge.bridge-nf-call-iptables=1
  if [[ -z $res ]]
  then
    echo "vm.swappiness = 0">> /etc/sysctl.conf
  fi
  echo "1" > /proc/sys/net/bridge/bridge-nf-call-iptables
  echo "1" > /proc/sys/net/ipv4/ip_forward >/dev/null

  systemctl enable kubelet
  systemctl start kubelet
}

function init-master()
{
  yum install -y docker-ce-19.03.5 kubeadm-1.16.1 kubectl-1.16.1 kubelet-1.16.1 openvswitch-2.11.0 openvswitch-ipsec-2.11.0 openvswitch-ovn-central-2.11.0 openvswitch-ovn-common-2.11.0 openvswitch-ovn-host-2.11.0 openvswitch-ovn-vtep-2.11.0 
  systemctl enable docker
  systemctl start  docker
  systemctl enable openvswitch
  systemctl start  openvswitch
}

function init-node()
{
  yum install -y docker-ce-19.03.5 kubeadm-1.16.1 kubectl-1.16.1 kubelet-1.16.1 openvswitch-2.11.0 openvswitch-ipsec-2.11.0 openvswitch-ovn-central-2.11.0 openvswitch-ovn-common-2.11.0 openvswitch-ovn-host-2.11.0 openvswitch-ovn-vtep-2.11.0 virt-manager-1.5.0 libvirt-4.5.0 qemu-kvm-ev-2.12.0
  systemctl enable docker
  systemctl start  docker
  systemctl enable openvswitch
  systemctl start  openvswitch
  systemctl enable libvirtd
  systemctl start  libvirtd
}

function setup-master()
{

  ## init
  init-env
  
  ## Kubernetes
  kubeadm init --config /cloudplus/kubeadm.yaml 
 
  rm -rf $HOME/.kube
  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config
  iptables -P FORWARD ACCEPT

  ## Calico
  for img in `cat /cloudplus/calico.yaml  | grep image |awk -F"image:" '{print$2}'`
  do
    echo "docker pull "$img
    docker pull $img
  done

  podcidr=$(kubeadm config view | grep podSubnet | awk -F": " '{print$2}')
  rm -rf calico.yaml
  cp /cloudplus/calico.yaml calico.yaml
  sed -i "s:POD_CIDR:${podcidr}:g" calico.yaml
  kubectl create -f calico.yaml
  rm -rf calico.yaml

  ## Plugins

  for plugin in `ls /cloudplus/ | grep kubevirt`
  do
    kubectl apply -f /cloudplus/$plugin
  done

  ## Network
  kubeovn-adm start-central 
}

function setup-node()
{
  # start our instances
  kubectl apply -f /cloudplus/node.yaml
  kubeovn-adm start-worker
}

function cmddesc()
{
  echo -e "Welcome to kubevirt-ctl, the install plugin for Kubernetes."
  echo -e "kubevirt-ctl: missing command name (use --help for help)\n"
}


function help()
{
  cmddesc
  echo -e "Commands:"
  echo -e "  init-master   :\t(Init) : Install softwares for Kubernetes Master"
  echo -e "  init-node     :\t(Init) : Install softwares for Kubernetes Node"
  echo -e "  setup-master  :\t(Setup): Install Kubernetes Master"
  echo -e "  setup-node    :\t(Setup): Install Kubernetes Node"
}


case $1 in
  "init-master")
    init-master $*
    ;;
  "init-node")
    init-node $*
    ;;
  "setup-master")
    setup-master $*
    ;;
  "setup-node")
    setup-node $*
    ;;
  "--help")
    help
    ;;
  *)
  help
  ;;
esac
