#!/bin/bash
##############################################
##
##  Copyright (2019,) Institute of Software
##       Chinese Academy of Sciences
##           wuheng@iscas.ac.cn
##
##############################################

num=$(head -n 20 /dev/urandom | cksum | cut -f1 -d ' ')

vname=$(echo $* | awk -F"--name" '{print$2}' | awk '{print$1}')
iname=$(echo $* | awk -F"--name" '{print$2}' | awk '{print$1}')

kubectl get vmi $iname -o yaml > $iname_$num.yaml

sed -i "s/VirtualMachineImage/VirtualMachine/g" $iname_$num.yaml
sed -i "s/name: $vname/name: $iname/g" $iname_$num.yaml

kubectl apply -f $iname_$num.yaml
kubectl delete vmi $iname
rm -f $iname_$num.yaml
