---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachines.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.domain.uuid.text
    name: UUID
    type: string
  - JSONPath: .spec.domain._type
    name: TYPE
    type: string
  - JSONPath: .spec.domain.vcpu.current
    name: CPU
    type: string
  - JSONPath: .spec.domain.memory.text
    name: RAM(KB)
    type: string
  - JSONPath: .spec.status.conditions.state.waiting.reason
    name: STATUS
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  - JSONPath: .spec.nodeName
    name: NODE
    type: string
  - JSONPath: .spec.image
    name: IMAGE
    type: string
  group: cloudplus.io
  names:
    kind: VirtualMachine
    plural: virtualmachines
    shortNames:
    - vm
    - vms
    singular: virtualmachine
  scope: Namespaced
  version: v1alpha3
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachinenetworks.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.VirtualMachineNetwork.type
    name: TYPE
    type: string
  - JSONPath: .spec.nodeName
    name: NODE
    type: string
  group: cloudplus.io
  names:
    kind: VirtualMachineNetwork
    plural: virtualmachinenetworks
    shortNames:
    - vmn
    - vmns
    singular: virtualmachinenetwork
  scope: Namespaced
  version: v1alpha3
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachineimages.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.domain.uuid.text
    name: UUID
    type: string
  - JSONPath: .spec.status.conditions.state.waiting.reason
    name: STATUS
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  - JSONPath: .spec.nodeName
    name: NODE
    type: string
  - JSONPath: .spec.image
    name: IMAGE
    type: string
  group: cloudplus.io
  names:
    kind: VirtualMachineImage
    plural: virtualmachineimages
    shortNames:
    - vmi
    - vmis
    singular: virtualmachineimage
  scope: Namespaced
  version: v1alpha3
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachinedisks.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.volume.target.format._type
    name: TYPE
    type: string  
  - JSONPath: .spec.volume.target.path.text
    name: PATH
    type: string  
  - JSONPath: .spec.status.conditions.state.waiting.reason
    name: STATUS
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  - JSONPath: .spec.nodeName
    name: NODE
    type: string
  group: cloudplus.io
  names:
    kind: VirtualMachineDisk
    plural: virtualmachinedisks
    shortNames:
    - vmd
    - vmds
    singular: virtualmachinedisk
  scope: Namespaced
  version: v1alpha3
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachinediskimages.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.volume.target.format._type
    name: TYPE
    type: string  
  - JSONPath: .spec.volume.target.path.text
    name: PATH
    type: string  
  - JSONPath: .spec.status.conditions.state.waiting.reason
    name: STATUS
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  - JSONPath: .spec.nodeName
    name: NODE
    type: string
  group: cloudplus.io
  names:
    kind: VirtualMachineDiskImage
    plural: virtualmachinediskimages
    shortNames:
    - vmdi
    - vmdis
    singular: virtualmachinediskimage
  scope: Namespaced
  version: v1alpha3
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachinesnapshots.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.domainsnapshot.name.text
    name: NAME
    type: string
  - JSONPath: .spec.domainsnapshot.domain.name.text
    name: VM
    type: string  
  - JSONPath: .spec.status.conditions.state.waiting.reason
    name: STATUS
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  - JSONPath: .spec.nodeName
    name: NODE
    type: string
  group: cloudplus.io
  names:
    kind: VirtualMachineSnapshot
    plural: virtualmachinesnapshots
    shortNames:
    - vmsn
    - vmsns
    singular: virtualmachinesnapshot
  scope: Namespaced
  version: v1alpha3
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachinepools.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.pool.uuid
    name: UUID
    type: string  
  - JSONPath: .spec.pool.path
    name: PATH
    type: string
  - JSONPath: .spec.pool.autostart
    name: AUTOSTART
    type: string
  - JSONPath: .spec.pool.capacity
    name: CAPACITY
    type: integer
  - JSONPath: .spec.pool.available
    name: AVAILABLE
    type: integer
  - JSONPath: .spec.pool.state
    name: STATE
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  - JSONPath: .spec.nodeName
    name: NODE
    type: string
  - JSONPath: .spec.status.conditions.state.waiting.reason
    name: STATUS
    type: string
  group: cloudplus.io
  names:
    kind: VirtualMachinePool
    plural: virtualmachinepools
    shortNames:
    - vmp
    - vmps
    singular: virtualmachinepool
  scope: Namespaced
  version: v1alpha3
